# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_for_convert.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #22222e\n"
" ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 300))
        self.frame.setStyleSheet("background-color: green\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(250, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono for Powerline")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(310, 70, 160, 160))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_2.setObjectName("label_2")
        self.input_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.input_currency.setGeometry(QtCore.QRect(250, 350, 300, 60))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono for Powerline")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_currency.setFont(font)
        self.input_currency.setStyleSheet("background-color: 22332e;\n"
"border: 2px;\n"
"border-radius: 30px;\n"
"color: black;")
        self.input_currency.setText("")
        self.input_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.input_currency.setObjectName("input_currency")
        self.output_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.output_currency.setGeometry(QtCore.QRect(250, 470, 300, 60))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono for Powerline")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_currency.setFont(font)
        self.output_currency.setStyleSheet("background-color: 22332e;\n"
"border: 2px;\n"
"border-radius: 30px;\n"
"color: black;")
        self.output_currency.setText("")
        self.output_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.output_currency.setObjectName("output_currency")
        self.comboBox_output = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_output.setGeometry(QtCore.QRect(320, 430, 150, 26))
        self.comboBox_output.setStyleSheet("background-color: 22334e;\n"
"color: black;")
        self.comboBox_output.setObjectName("comboBox_output")
        self.comboBox_input = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_input.setGeometry(QtCore.QRect(320, 310, 150, 26))
        self.comboBox_input.setStyleSheet("background-color: 22334e;\n"
"color: black;")
        self.comboBox_input.setObjectName("comboBox_input")
        self.convert = QtWidgets.QPushButton(self.centralwidget)
        self.convert.setGeometry(QtCore.QRect(280, 550, 250, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono for Powerline")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.convert.setFont(font)
        self.convert.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"    color: white;\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border-radius: 30;\n"
"}")
        self.convert.setObjectName("convert")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конвертер Валют"))
        self.convert.setText(_translate("MainWindow", "Конвертировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
